dest: ~/Documents/Scolaire
dirs:
  - ~/usb
  - ~/Documents/Scolaire


once: false
sleep: 1000
timeinfo: true
static_mode: false

codes:
  chin: Chinois
  en:   Anglais
  eps:  EPS
  gr:   Grec
  pc:   Physique-Chimie
  ses:  Sciences Économiques et Sociales
  svt:  SVT
  glb:  Global
  fr:   Français
  hg:   Histoire-Géographie
  mt:   Mathématiques
  info: Informatique
  vdc:  Vie de Classe