---
dest: ~/Scolaire
dirs:
  - ~/Scolaire
  - ~/usb
once: false
timeinfo: false
static_mode: false
sleep: 1000
codes:
  hg: Histoire-Géographie
  ses: Sciences Économiques et Sociales
  info: Informatique
  en: Anglais
  chin: Chinois
  mt: Mathématiques
  svt: SVT
  eps: EPS
  pc: Physique-Chimie
  glb: Global
  vdc: Vie de Classe
  gr: Grec
  fr: Français
